### ISSUE TITLE
Summary plots not loading for new forecast hour convention

### ISSUE THREAD

**Issue by lesnow93** [SERVIR/hiwat_model_viewer#15]
In Ensemble page, the Summaries are not loading correctly for the more recent forecasts initialized at 1200, going out to 54 hours total.  The new Summaries are being generated ending at forecast hours 30 (day-1) and 54 (day-2) instead of ending at forecast hours 24 and 48 as in the previous 2 years of experiments.  Perhaps the 24 and 48 were hard-coded into the HMV?

**Comment by billyz313** [comment]
fixed
