### ISSUE TITLE
Animation controls have larger view in Chrome than in Firefox

### ISSUE THREAD

**Issue by lesnow93** [SERVIR/hiwat_model_viewer#16]
The animation control buttons, scroll bar, and labels have a slightly larger default view in Chrome than in Firefox.  As a result, some of the chrome animation controls carry over onto a new line below.  For example, in the Ensemble/Deterministic toggle, the deterministic label is on the next line below the toggle in Chrome, but appears more cleanly beside the toggle when viewed in Firefox.  The same goes for the calendar icon, which is below the "Initialized: " label.

**Comment by billyz313** [comment]
The layout has been adjusted to fix the issue
