### ISSUE TITLE
Deterministic upper-level temperatures not loading

### ISSUE THREAD

**Issue by lesnow93** [SERVIR/hiwat_model_viewer#18]
all levels not loading (200mb, 300, 500, 700, 850, 925) for Temp, GeoPotHgt, Wind fields.

**Comment by billyz313** [comment]
I think this is a duplicate bug that was just fixed in #17 , please clear ur browser cache then confirm, if it's not fixed please give a menu path (like u did in the other issue) that i can follow to open the broken image.

**Comment by lesnow93** [comment]
Hi Billy,

Almost all of the upper-level fields were not displaying properly.  I put winds in one, and temperature in another item.

-Jon
