### ISSUE TITLE
Reverts back to most recent date when toggling between Ensemble and Deterministic

### ISSUE THREAD

**Issue by lesnow93** [SERVIR/hiwat_model_viewer#22]
Previously, the HMV would let me load up an archived date, and initially display the Ensemble page.  Then I could toggle to Deterministic to load the fields for the same archive date.  Now, whenever I toggle between Ensemble or Deterministic while viewing an archived date, it reverts back to the present (or most recently available) date, thereby requiring an extra step to go back into the calendar to load the archived date of interest.

**Comment by billyz313** [comment]
Thank you, this is now fixed.
